In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
Bk = np.loadtxt("../data/BK_bao_only.txt")

In [8]:
def Bk_int(k1, k2, k3, a):
    ik1 = int(k1/0.01)
    ik2 = int(k2/0.01)
    ik3 = int(k3/0.01)
    

array([0.005, 0.015, 0.025, ..., 0.285, 0.295, 0.295])

In [19]:
Bk[0,-10:]

array([0.275, 0.275, 0.275, 0.275, 0.275, 0.275, 0.285, 0.285, 0.285,
       0.295])

In [20]:
Bk[1,-10:]

array([0.275, 0.275, 0.275, 0.285, 0.285, 0.295, 0.285, 0.285, 0.295,
       0.295])

In [21]:
Bk[2,-10:]

array([0.275, 0.285, 0.295, 0.285, 0.295, 0.295, 0.285, 0.295, 0.295,
       0.295])